/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../app/app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './rich-grid.component.ngfactory';
import * as import11 from './rich-grid-declarative.component.ngfactory';
import * as import12 from './from-component.component.ngfactory';
import * as import13 from './from-rich.component.ngfactory';
import * as import14 from './editor-component.component.ngfactory';
import * as import15 from './floating-row-renderer.component.ngfactory';
import * as import16 from './full-width-renderer.component.ngfactory';
import * as import17 from './group-row-renderer.component.ngfactory';
import * as import18 from './filter-component.component.ngfactory';
import * as import19 from '../../app/rich-grid.component';
import * as import20 from '../../app/rich-grid-declarative.component';
import * as import21 from '../../app/from-component.component';
import * as import22 from '../../app/from-rich.component';
import * as import23 from '../../app/editor-component.component';
import * as import24 from '../../app/floating-row-renderer.component';
import * as import25 from '../../app/full-width-renderer.component';
import * as import26 from '../../app/group-row-renderer.component';
import * as import27 from '../../app/filter-component.component';
export class Wrapper_AppComponent {
  context:import0.AppComponent;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.AppComponent();
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = (null as any);
class _View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _AppComponent_0_4:Wrapper_AppComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent_Host0,renderType_AppComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'my-app',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AppComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AppComponent_0_4 = new Wrapper_AppComponent();
    this._appEl_0.initComponent(this._AppComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._AppComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._AppComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AppComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_AppComponent_Host === (null as any))) { (renderType_AppComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_AppComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppComponentNgFactory:import9.ComponentFactory<import0.AppComponent> = new import9.ComponentFactory<import0.AppComponent>('my-app',viewFactory_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = ([] as any[]);
var renderType_AppComponent:import2.RenderComponentType = (null as any);
class _View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _RichGridComponent_0_4:import10.Wrapper_RichGridComponent;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _RichGridDeclarativeComponent_4_4:import11.Wrapper_RichGridDeclarativeComponent;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  /*private*/ _appEl_8:import3.AppElement;
  _FromComponentComponent_8_4:import12.Wrapper_FromComponentComponent;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import3.AppElement;
  _FromRichComponent_15_4:import13.Wrapper_FromRichComponent;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  /*private*/ _appEl_19:import3.AppElement;
  _EditorComponent_19_4:import14.Wrapper_EditorComponent;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import3.AppElement;
  _WithFloatingRowComponent_23_4:import15.Wrapper_WithFloatingRowComponent;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  /*private*/ _appEl_27:import3.AppElement;
  _WithFullWidthComponent_27_4:import16.Wrapper_WithFullWidthComponent;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  /*private*/ _appEl_31:import3.AppElement;
  _WithGroupRowComponent_31_4:import17.Wrapper_WithGroupRowComponent;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  /*private*/ _appEl_35:import3.AppElement;
  _FilterComponentComponent_35_4:import18.Wrapper_FilterComponentComponent;
  _text_36:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent0,renderType_AppComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'rich-grid',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import10.viewFactory_RichGridComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._RichGridComponent_0_4 = new import10.Wrapper_RichGridComponent();
    this._appEl_0.initComponent(this._RichGridComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._RichGridComponent_0_4.context,([] as any[]),(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,parentRenderNode,'hr',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_4 = import4.createRenderElement(this.renderer,parentRenderNode,'ag-rich-grid-declarative',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_4 = new import3.AppElement(4,(null as any),this,this._el_4);
    var compView_4:any = import11.viewFactory_RichGridDeclarativeComponent0(this.viewUtils,this.injector(4),this._appEl_4);
    this._RichGridDeclarativeComponent_4_4 = new import11.Wrapper_RichGridDeclarativeComponent();
    this._appEl_4.initComponent(this._RichGridDeclarativeComponent_4_4.context,([] as any[]),compView_4);
    compView_4.create(this._RichGridDeclarativeComponent_4_4.context,([] as any[]),(null as any));
    this._text_5 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_6 = import4.createRenderElement(this.renderer,parentRenderNode,'hr',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_8 = import4.createRenderElement(this.renderer,parentRenderNode,'ag-from-component',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_8 = new import3.AppElement(8,(null as any),this,this._el_8);
    var compView_8:any = import12.viewFactory_FromComponentComponent0(this.viewUtils,this.injector(8),this._appEl_8);
    this._FromComponentComponent_8_4 = new import12.Wrapper_FromComponentComponent();
    this._appEl_8.initComponent(this._FromComponentComponent_8_4.context,([] as any[]),compView_8);
    compView_8.create(this._FromComponentComponent_8_4.context,([] as any[]),(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_10 = import4.createRenderElement(this.renderer,parentRenderNode,'hr',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_11 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._text_12 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_13 = import4.createRenderElement(this.renderer,parentRenderNode,'hr',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_14 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_15 = import4.createRenderElement(this.renderer,parentRenderNode,'ag-from-rich-component',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_15 = new import3.AppElement(15,(null as any),this,this._el_15);
    var compView_15:any = import13.viewFactory_FromRichComponent0(this.viewUtils,this.injector(15),this._appEl_15);
    this._FromRichComponent_15_4 = new import13.Wrapper_FromRichComponent();
    this._appEl_15.initComponent(this._FromRichComponent_15_4.context,([] as any[]),compView_15);
    compView_15.create(this._FromRichComponent_15_4.context,([] as any[]),(null as any));
    this._text_16 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_17 = import4.createRenderElement(this.renderer,parentRenderNode,'hr',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_18 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_19 = import4.createRenderElement(this.renderer,parentRenderNode,'ag-editor-component',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_19 = new import3.AppElement(19,(null as any),this,this._el_19);
    var compView_19:any = import14.viewFactory_EditorComponent0(this.viewUtils,this.injector(19),this._appEl_19);
    this._EditorComponent_19_4 = new import14.Wrapper_EditorComponent();
    this._appEl_19.initComponent(this._EditorComponent_19_4.context,([] as any[]),compView_19);
    compView_19.create(this._EditorComponent_19_4.context,([] as any[]),(null as any));
    this._text_20 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_21 = import4.createRenderElement(this.renderer,parentRenderNode,'hr',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_22 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_23 = import4.createRenderElement(this.renderer,parentRenderNode,'ag-floating-row-renderer-component',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_23 = new import3.AppElement(23,(null as any),this,this._el_23);
    var compView_23:any = import15.viewFactory_WithFloatingRowComponent0(this.viewUtils,this.injector(23),this._appEl_23);
    this._WithFloatingRowComponent_23_4 = new import15.Wrapper_WithFloatingRowComponent();
    this._appEl_23.initComponent(this._WithFloatingRowComponent_23_4.context,([] as any[]),compView_23);
    compView_23.create(this._WithFloatingRowComponent_23_4.context,([] as any[]),(null as any));
    this._text_24 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_25 = import4.createRenderElement(this.renderer,parentRenderNode,'hr',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_26 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_27 = import4.createRenderElement(this.renderer,parentRenderNode,'ag-full-width-renderer-component',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_27 = new import3.AppElement(27,(null as any),this,this._el_27);
    var compView_27:any = import16.viewFactory_WithFullWidthComponent0(this.viewUtils,this.injector(27),this._appEl_27);
    this._WithFullWidthComponent_27_4 = new import16.Wrapper_WithFullWidthComponent();
    this._appEl_27.initComponent(this._WithFullWidthComponent_27_4.context,([] as any[]),compView_27);
    compView_27.create(this._WithFullWidthComponent_27_4.context,([] as any[]),(null as any));
    this._text_28 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_29 = import4.createRenderElement(this.renderer,parentRenderNode,'hr',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_30 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_31 = import4.createRenderElement(this.renderer,parentRenderNode,'ag-group-row-renderer-component',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_31 = new import3.AppElement(31,(null as any),this,this._el_31);
    var compView_31:any = import17.viewFactory_WithGroupRowComponent0(this.viewUtils,this.injector(31),this._appEl_31);
    this._WithGroupRowComponent_31_4 = new import17.Wrapper_WithGroupRowComponent();
    this._appEl_31.initComponent(this._WithGroupRowComponent_31_4.context,([] as any[]),compView_31);
    compView_31.create(this._WithGroupRowComponent_31_4.context,([] as any[]),(null as any));
    this._text_32 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_33 = import4.createRenderElement(this.renderer,parentRenderNode,'hr',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_34 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_35 = import4.createRenderElement(this.renderer,parentRenderNode,'ag-filter-component',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_35 = new import3.AppElement(35,(null as any),this,this._el_35);
    var compView_35:any = import18.viewFactory_FilterComponentComponent0(this.viewUtils,this.injector(35),this._appEl_35);
    this._FilterComponentComponent_35_4 = new import18.Wrapper_FilterComponentComponent();
    this._appEl_35.initComponent(this._FilterComponentComponent_35_4.context,([] as any[]),compView_35);
    compView_35.create(this._FilterComponentComponent_35_4.context,([] as any[]),(null as any));
    this._text_36 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.RichGridComponent) && (0 === requestNodeIndex))) { return this._RichGridComponent_0_4.context; }
    if (((token === import20.RichGridDeclarativeComponent) && (4 === requestNodeIndex))) { return this._RichGridDeclarativeComponent_4_4.context; }
    if (((token === import21.FromComponentComponent) && (8 === requestNodeIndex))) { return this._FromComponentComponent_8_4.context; }
    if (((token === import22.FromRichComponent) && (15 === requestNodeIndex))) { return this._FromRichComponent_15_4.context; }
    if (((token === import23.EditorComponent) && (19 === requestNodeIndex))) { return this._EditorComponent_19_4.context; }
    if (((token === import24.WithFloatingRowComponent) && (23 === requestNodeIndex))) { return this._WithFloatingRowComponent_23_4.context; }
    if (((token === import25.WithFullWidthComponent) && (27 === requestNodeIndex))) { return this._WithFullWidthComponent_27_4.context; }
    if (((token === import26.WithGroupRowComponent) && (31 === requestNodeIndex))) { return this._WithGroupRowComponent_31_4.context; }
    if (((token === import27.FilterComponentComponent) && (35 === requestNodeIndex))) { return this._FilterComponentComponent_35_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._RichGridComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this._RichGridDeclarativeComponent_4_4.detectChangesInInputProps(this,this._el_4,throwOnChange);
    this._FromComponentComponent_8_4.detectChangesInInputProps(this,this._el_8,throwOnChange);
    this._FromRichComponent_15_4.detectChangesInInputProps(this,this._el_15,throwOnChange);
    this._EditorComponent_19_4.detectChangesInInputProps(this,this._el_19,throwOnChange);
    this._WithFloatingRowComponent_23_4.detectChangesInInputProps(this,this._el_23,throwOnChange);
    this._WithFullWidthComponent_27_4.detectChangesInInputProps(this,this._el_27,throwOnChange);
    this._WithGroupRowComponent_31_4.detectChangesInInputProps(this,this._el_31,throwOnChange);
    this._FilterComponentComponent_35_4.detectChangesInInputProps(this,this._el_35,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._RichGridComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this._RichGridDeclarativeComponent_4_4.detectChangesInHostProps(this,this._el_4,throwOnChange);
    this._FromComponentComponent_8_4.detectChangesInHostProps(this,this._el_8,throwOnChange);
    this._FromRichComponent_15_4.detectChangesInHostProps(this,this._el_15,throwOnChange);
    this._EditorComponent_19_4.detectChangesInHostProps(this,this._el_19,throwOnChange);
    this._WithFloatingRowComponent_23_4.detectChangesInHostProps(this,this._el_23,throwOnChange);
    this._WithFullWidthComponent_27_4.detectChangesInHostProps(this,this._el_27,throwOnChange);
    this._WithGroupRowComponent_31_4.detectChangesInHostProps(this,this._el_31,throwOnChange);
    this._FilterComponentComponent_35_4.detectChangesInHostProps(this,this._el_35,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_AppComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.AppComponent> {
  if ((renderType_AppComponent === (null as any))) { (renderType_AppComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,styles_AppComponent,{})); }
  return new _View_AppComponent0(viewUtils,parentInjector,declarationEl);
}