/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../app/app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/router/src/router_module';
import * as import8 from 'ag-grid-ng2/lib/aggrid.module';
import * as import9 from '../../app/ratio.module';
import * as import10 from '../../app/clickable.module';
import * as import11 from '@angular/common/src/localization';
import * as import12 from '@angular/core/src/application_init';
import * as import13 from '@angular/core/src/testability/testability';
import * as import14 from '@angular/core/src/application_ref';
import * as import15 from '@angular/core/src/linker/compiler';
import * as import16 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import17 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import18 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import19 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import20 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import21 from '@angular/core/src/linker/view_utils';
import * as import22 from '@angular/platform-browser/src/browser/title';
import * as import23 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import24 from '@angular/common/src/location/location';
import * as import25 from '@angular/router/src/url_tree';
import * as import26 from '@angular/router/src/router_outlet_map';
import * as import27 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import28 from '@angular/router/src/router_preloader';
import * as import29 from 'ag-grid-ng2/lib/ng2ComponentFactory';
import * as import30 from 'ag-grid-ng2/lib/ng2FrameworkFactory';
import * as import31 from '@angular/core/src/di/injector';
import * as import32 from './rich-grid.component.ngfactory';
import * as import33 from './rich-grid-declarative.component.ngfactory';
import * as import34 from './from-component.component.ngfactory';
import * as import35 from './from-rich.component.ngfactory';
import * as import36 from './editor-component.component.ngfactory';
import * as import37 from './floating-row-renderer.component.ngfactory';
import * as import38 from './full-width-renderer.component.ngfactory';
import * as import39 from './group-row-renderer.component.ngfactory';
import * as import40 from './filter-component.component.ngfactory';
import * as import41 from './square.component.ngfactory';
import * as import42 from './cube.component.ngfactory';
import * as import43 from './params.component.ngfactory';
import * as import44 from './ratio.parent.component.ngfactory';
import * as import45 from './clickable.parent.component.ngfactory';
import * as import46 from './numeric-editor.component.ngfactory';
import * as import47 from './mood-editor.component.ngfactory';
import * as import48 from './mood-renderer.component.ngfactory';
import * as import49 from './styled-renderer.component.ngfactory';
import * as import50 from './name-age-renderer.component.ngfactory';
import * as import51 from './medal-renderer.component.ngfactory';
import * as import52 from './partial-match-filter.component.ngfactory';
import * as import53 from './app.component.ngfactory';
import * as import54 from '@angular/core/src/application_tokens';
import * as import55 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import56 from '@angular/platform-browser/src/dom/events/key_events';
import * as import57 from '@angular/core/src/zone/ng_zone';
import * as import58 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import59 from '@angular/common/src/location/platform_location';
import * as import60 from '@angular/common/src/location/location_strategy';
import * as import61 from '../../app/rich-grid.component';
import * as import62 from '../../app/rich-grid-declarative.component';
import * as import63 from '../../app/from-component.component';
import * as import64 from '../../app/from-rich.component';
import * as import65 from '../../app/editor-component.component';
import * as import66 from '../../app/floating-row-renderer.component';
import * as import67 from '../../app/full-width-renderer.component';
import * as import68 from '../../app/group-row-renderer.component';
import * as import69 from '../../app/filter-component.component';
import * as import70 from '@angular/router/src/router';
import * as import71 from '@angular/core/src/console';
import * as import72 from '@angular/core/src/i18n/tokens';
import * as import73 from '@angular/core/src/error_handler';
import * as import74 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import75 from '@angular/platform-browser/src/dom/animation_driver';
import * as import76 from '@angular/core/src/render/api';
import * as import77 from '@angular/core/src/security';
import * as import78 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import79 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import80 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import81 from '@angular/router/src/router_config_loader';
import * as import82 from '@angular/router/src/router_state';
import * as import83 from 'ag-grid-ng2/lib/baseComponentFactory';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _ROUTER_FORROOT_GUARD_5:any;
  _RouterModule_6:import7.RouterModule;
  _AgGridModule_7:import8.AgGridModule;
  _RatioModule_8:import9.RatioModule;
  _ClickableModule_9:import10.ClickableModule;
  _AppModule_10:import1.AppModule;
  __LOCALE_ID_11:any;
  __NgLocalization_12:import11.NgLocaleLocalization;
  _ErrorHandler_13:any;
  _ApplicationInitStatus_14:import12.ApplicationInitStatus;
  _Testability_15:import13.Testability;
  _ApplicationRef__16:import14.ApplicationRef_;
  __ApplicationRef_17:any;
  __Compiler_18:import15.Compiler;
  __APP_ID_19:any;
  __DOCUMENT_20:any;
  __HAMMER_GESTURE_CONFIG_21:import16.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_22:any[];
  __EventManager_23:import17.EventManager;
  __DomSharedStylesHost_24:import18.DomSharedStylesHost;
  __AnimationDriver_25:any;
  __DomRootRenderer_26:import19.DomRootRenderer_;
  __RootRenderer_27:any;
  __DomSanitizer_28:import20.DomSanitizerImpl;
  __Sanitizer_29:any;
  __ViewUtils_30:import21.ViewUtils;
  __IterableDiffers_31:any;
  __KeyValueDiffers_32:any;
  __SharedStylesHost_33:any;
  __Title_34:import22.Title;
  __RadioControlRegistry_35:import23.RadioControlRegistry;
  __ROUTER_CONFIGURATION_36:any;
  __LocationStrategy_37:any;
  __Location_38:import24.Location;
  __UrlSerializer_39:import25.DefaultUrlSerializer;
  __RouterOutletMap_40:import26.RouterOutletMap;
  __NgModuleFactoryLoader_41:import27.SystemJsNgModuleLoader;
  __ROUTES_42:any[];
  __Router_43:any;
  __ActivatedRoute_44:any;
  _NoPreloading_45:import28.NoPreloading;
  _PreloadingStrategy_46:any;
  _RouterPreloader_47:import28.RouterPreloader;
  __PreloadAllModules_48:import28.PreloadAllModules;
  __APP_BOOTSTRAP_LISTENER_49:any[];
  __Ng2ComponentFactory_50:import29.Ng2ComponentFactory;
  __BaseComponentFactory_51:any;
  __Ng2FrameworkFactory_52:import30.Ng2FrameworkFactory;
  constructor(parent:import31.Injector) {
    super(parent,[
      import32.RichGridComponentNgFactory,
      import33.RichGridDeclarativeComponentNgFactory,
      import34.FromComponentComponentNgFactory,
      import35.FromRichComponentNgFactory,
      import36.EditorComponentNgFactory,
      import37.WithFloatingRowComponentNgFactory,
      import38.WithFullWidthComponentNgFactory,
      import39.WithGroupRowComponentNgFactory,
      import40.FilterComponentComponentNgFactory,
      import41.SquareComponentNgFactory,
      import42.CubeComponentNgFactory,
      import43.ParamsComponentNgFactory,
      import44.RatioParentComponentNgFactory,
      import45.ClickableParentComponentNgFactory,
      import46.NumericEditorComponentNgFactory,
      import47.MoodEditorComponentNgFactory,
      import48.MoodRendererComponentNgFactory,
      import49.StyledComponentNgFactory,
      import50.NameAndAgeRendererComponentNgFactory,
      import51.MedalRendererComponentNgFactory,
      import52.PartialMatchFilterComponentNgFactory,
      import53.AppComponentNgFactory
    ]
    ,[import53.AppComponentNgFactory]);
  }
  get _LOCALE_ID_11():any {
    if ((this.__LOCALE_ID_11 == (null as any))) { (this.__LOCALE_ID_11 = 'en-US'); }
    return this.__LOCALE_ID_11;
  }
  get _NgLocalization_12():import11.NgLocaleLocalization {
    if ((this.__NgLocalization_12 == (null as any))) { (this.__NgLocalization_12 = new import11.NgLocaleLocalization(this._LOCALE_ID_11)); }
    return this.__NgLocalization_12;
  }
  get _ApplicationRef_17():any {
    if ((this.__ApplicationRef_17 == (null as any))) { (this.__ApplicationRef_17 = this._ApplicationRef__16); }
    return this.__ApplicationRef_17;
  }
  get _Compiler_18():import15.Compiler {
    if ((this.__Compiler_18 == (null as any))) { (this.__Compiler_18 = new import15.Compiler()); }
    return this.__Compiler_18;
  }
  get _APP_ID_19():any {
    if ((this.__APP_ID_19 == (null as any))) { (this.__APP_ID_19 = import54._appIdRandomProviderFactory()); }
    return this.__APP_ID_19;
  }
  get _DOCUMENT_20():any {
    if ((this.__DOCUMENT_20 == (null as any))) { (this.__DOCUMENT_20 = import4._document()); }
    return this.__DOCUMENT_20;
  }
  get _HAMMER_GESTURE_CONFIG_21():import16.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_21 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_21 = new import16.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_21;
  }
  get _EVENT_MANAGER_PLUGINS_22():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_22 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_22 = [
      new import55.DomEventsPlugin(),
      new import56.KeyEventsPlugin(),
      new import16.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_21)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_22;
  }
  get _EventManager_23():import17.EventManager {
    if ((this.__EventManager_23 == (null as any))) { (this.__EventManager_23 = new import17.EventManager(this._EVENT_MANAGER_PLUGINS_22,this.parent.get(import57.NgZone))); }
    return this.__EventManager_23;
  }
  get _DomSharedStylesHost_24():import18.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_24 == (null as any))) { (this.__DomSharedStylesHost_24 = new import18.DomSharedStylesHost(this._DOCUMENT_20)); }
    return this.__DomSharedStylesHost_24;
  }
  get _AnimationDriver_25():any {
    if ((this.__AnimationDriver_25 == (null as any))) { (this.__AnimationDriver_25 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_25;
  }
  get _DomRootRenderer_26():import19.DomRootRenderer_ {
    if ((this.__DomRootRenderer_26 == (null as any))) { (this.__DomRootRenderer_26 = new import19.DomRootRenderer_(this._DOCUMENT_20,this._EventManager_23,this._DomSharedStylesHost_24,this._AnimationDriver_25)); }
    return this.__DomRootRenderer_26;
  }
  get _RootRenderer_27():any {
    if ((this.__RootRenderer_27 == (null as any))) { (this.__RootRenderer_27 = import58._createConditionalRootRenderer(this._DomRootRenderer_26,this.parent.get(import58.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_27;
  }
  get _DomSanitizer_28():import20.DomSanitizerImpl {
    if ((this.__DomSanitizer_28 == (null as any))) { (this.__DomSanitizer_28 = new import20.DomSanitizerImpl()); }
    return this.__DomSanitizer_28;
  }
  get _Sanitizer_29():any {
    if ((this.__Sanitizer_29 == (null as any))) { (this.__Sanitizer_29 = this._DomSanitizer_28); }
    return this.__Sanitizer_29;
  }
  get _ViewUtils_30():import21.ViewUtils {
    if ((this.__ViewUtils_30 == (null as any))) { (this.__ViewUtils_30 = new import21.ViewUtils(this._RootRenderer_27,this._APP_ID_19,this._Sanitizer_29)); }
    return this.__ViewUtils_30;
  }
  get _IterableDiffers_31():any {
    if ((this.__IterableDiffers_31 == (null as any))) { (this.__IterableDiffers_31 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_31;
  }
  get _KeyValueDiffers_32():any {
    if ((this.__KeyValueDiffers_32 == (null as any))) { (this.__KeyValueDiffers_32 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_32;
  }
  get _SharedStylesHost_33():any {
    if ((this.__SharedStylesHost_33 == (null as any))) { (this.__SharedStylesHost_33 = this._DomSharedStylesHost_24); }
    return this.__SharedStylesHost_33;
  }
  get _Title_34():import22.Title {
    if ((this.__Title_34 == (null as any))) { (this.__Title_34 = new import22.Title()); }
    return this.__Title_34;
  }
  get _RadioControlRegistry_35():import23.RadioControlRegistry {
    if ((this.__RadioControlRegistry_35 == (null as any))) { (this.__RadioControlRegistry_35 = new import23.RadioControlRegistry()); }
    return this.__RadioControlRegistry_35;
  }
  get _ROUTER_CONFIGURATION_36():any {
    if ((this.__ROUTER_CONFIGURATION_36 == (null as any))) { (this.__ROUTER_CONFIGURATION_36 = {}); }
    return this.__ROUTER_CONFIGURATION_36;
  }
  get _LocationStrategy_37():any {
    if ((this.__LocationStrategy_37 == (null as any))) { (this.__LocationStrategy_37 = import7.provideLocationStrategy(this.parent.get(import59.PlatformLocation),this.parent.get(import60.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_36)); }
    return this.__LocationStrategy_37;
  }
  get _Location_38():import24.Location {
    if ((this.__Location_38 == (null as any))) { (this.__Location_38 = new import24.Location(this._LocationStrategy_37)); }
    return this.__Location_38;
  }
  get _UrlSerializer_39():import25.DefaultUrlSerializer {
    if ((this.__UrlSerializer_39 == (null as any))) { (this.__UrlSerializer_39 = new import25.DefaultUrlSerializer()); }
    return this.__UrlSerializer_39;
  }
  get _RouterOutletMap_40():import26.RouterOutletMap {
    if ((this.__RouterOutletMap_40 == (null as any))) { (this.__RouterOutletMap_40 = new import26.RouterOutletMap()); }
    return this.__RouterOutletMap_40;
  }
  get _NgModuleFactoryLoader_41():import27.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_41 == (null as any))) { (this.__NgModuleFactoryLoader_41 = new import27.SystemJsNgModuleLoader(this._Compiler_18,this.parent.get(import27.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_41;
  }
  get _ROUTES_42():any[] {
      if ((this.__ROUTES_42 == (null as any))) { (this.__ROUTES_42 = [[
        {
          path: 'rich-grid',
          component: import61.RichGridComponent,
          data: {title: 'Rich Grid with Pure JavaScript'}
        }
        ,
        {
          path: 'rich-grid-declarative',
          component: import62.RichGridDeclarativeComponent,
          data: {title: 'Rich Grid with Declarative Markup'}
        }
        ,
        {
          path: 'from-component',
          component: import63.FromComponentComponent,
          data: {title: 'Using Dynamic Components'}
        }
        ,
        {
          path: 'from-rich-component',
          component: import64.FromRichComponent,
          data: {title: 'Using Dynamic Components - Richer Example'}
        }
        ,
        {
          path: 'editor-component',
          component: import65.EditorComponent,
          data: {title: 'Using Cell Editor Components'}
        }
        ,
        {
          path: 'floating-row',
          component: import66.WithFloatingRowComponent,
          data: {title: 'Using Floating Row Renderers'}
        }
        ,
        {
          path: 'full-width',
          component: import67.WithFullWidthComponent,
          data: {title: 'Using Full Width Renderers'}
        }
        ,
        {
          path: 'group-row',
          component: import68.WithGroupRowComponent,
          data: {title: 'Using Group Row Renderers'}
        }
        ,
        {
          path: 'filter',
          component: import69.FilterComponentComponent,
          data: {title: 'With Filters Components'}
        }
        ,
        {
          path: '',
          redirectTo: 'rich-grid',
          pathMatch: 'full'
        }

      ]
    ]); }
    return this.__ROUTES_42;
  }
  get _Router_43():any {
    if ((this.__Router_43 == (null as any))) { (this.__Router_43 = import7.setupRouter(this._ApplicationRef_17,this._UrlSerializer_39,this._RouterOutletMap_40,this._Location_38,this,this._NgModuleFactoryLoader_41,this._Compiler_18,this._ROUTES_42,this._ROUTER_CONFIGURATION_36)); }
    return this.__Router_43;
  }
  get _ActivatedRoute_44():any {
    if ((this.__ActivatedRoute_44 == (null as any))) { (this.__ActivatedRoute_44 = import7.rootRoute(this._Router_43)); }
    return this.__ActivatedRoute_44;
  }
  get _PreloadAllModules_48():import28.PreloadAllModules {
    if ((this.__PreloadAllModules_48 == (null as any))) { (this.__PreloadAllModules_48 = new import28.PreloadAllModules()); }
    return this.__PreloadAllModules_48;
  }
  get _APP_BOOTSTRAP_LISTENER_49():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_49 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_49 = [import7.initialRouterNavigation(this._Router_43,this._ApplicationRef_17,this._RouterPreloader_47,this._ROUTER_CONFIGURATION_36)]); }
    return this.__APP_BOOTSTRAP_LISTENER_49;
  }
  get _Ng2ComponentFactory_50():import29.Ng2ComponentFactory {
    if ((this.__Ng2ComponentFactory_50 == (null as any))) { (this.__Ng2ComponentFactory_50 = new import29.Ng2ComponentFactory(this)); }
    return this.__Ng2ComponentFactory_50;
  }
  get _BaseComponentFactory_51():any {
    if ((this.__BaseComponentFactory_51 == (null as any))) { (this.__BaseComponentFactory_51 = this._Ng2ComponentFactory_50); }
    return this.__BaseComponentFactory_51;
  }
  get _Ng2FrameworkFactory_52():import30.Ng2FrameworkFactory {
    if ((this.__Ng2FrameworkFactory_52 == (null as any))) { (this.__Ng2FrameworkFactory_52 = new import30.Ng2FrameworkFactory(this._BaseComponentFactory_51)); }
    return this.__Ng2FrameworkFactory_52;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._ROUTER_FORROOT_GUARD_5 = import7.provideForRootGuard(this.parent.get(import70.Router,(null as any)));
    this._RouterModule_6 = new import7.RouterModule(this._ROUTER_FORROOT_GUARD_5);
    this._AgGridModule_7 = new import8.AgGridModule();
    this._RatioModule_8 = new import9.RatioModule();
    this._ClickableModule_9 = new import10.ClickableModule();
    this._AppModule_10 = new import1.AppModule();
    this._ErrorHandler_13 = import4.errorHandler();
    this._ApplicationInitStatus_14 = new import12.ApplicationInitStatus(this.parent.get(import12.APP_INITIALIZER,(null as any)));
    this._Testability_15 = new import13.Testability(this.parent.get(import57.NgZone));
    this._ApplicationRef__16 = new import14.ApplicationRef_(this.parent.get(import57.NgZone),this.parent.get(import71.Console),this,this._ErrorHandler_13,this,this._ApplicationInitStatus_14,this.parent.get(import13.TestabilityRegistry,(null as any)),this._Testability_15);
    this._NoPreloading_45 = new import28.NoPreloading();
    this._PreloadingStrategy_46 = this._NoPreloading_45;
    this._RouterPreloader_47 = new import28.RouterPreloader(this._Router_43,this._NgModuleFactoryLoader_41,this._Compiler_18,this,this._PreloadingStrategy_46);
    return this._AppModule_10;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_5; }
    if ((token === import7.RouterModule)) { return this._RouterModule_6; }
    if ((token === import8.AgGridModule)) { return this._AgGridModule_7; }
    if ((token === import9.RatioModule)) { return this._RatioModule_8; }
    if ((token === import10.ClickableModule)) { return this._ClickableModule_9; }
    if ((token === import1.AppModule)) { return this._AppModule_10; }
    if ((token === import72.LOCALE_ID)) { return this._LOCALE_ID_11; }
    if ((token === import11.NgLocalization)) { return this._NgLocalization_12; }
    if ((token === import73.ErrorHandler)) { return this._ErrorHandler_13; }
    if ((token === import12.ApplicationInitStatus)) { return this._ApplicationInitStatus_14; }
    if ((token === import13.Testability)) { return this._Testability_15; }
    if ((token === import14.ApplicationRef_)) { return this._ApplicationRef__16; }
    if ((token === import14.ApplicationRef)) { return this._ApplicationRef_17; }
    if ((token === import15.Compiler)) { return this._Compiler_18; }
    if ((token === import54.APP_ID)) { return this._APP_ID_19; }
    if ((token === import74.DOCUMENT)) { return this._DOCUMENT_20; }
    if ((token === import16.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_21; }
    if ((token === import17.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_22; }
    if ((token === import17.EventManager)) { return this._EventManager_23; }
    if ((token === import18.DomSharedStylesHost)) { return this._DomSharedStylesHost_24; }
    if ((token === import75.AnimationDriver)) { return this._AnimationDriver_25; }
    if ((token === import19.DomRootRenderer)) { return this._DomRootRenderer_26; }
    if ((token === import76.RootRenderer)) { return this._RootRenderer_27; }
    if ((token === import20.DomSanitizer)) { return this._DomSanitizer_28; }
    if ((token === import77.Sanitizer)) { return this._Sanitizer_29; }
    if ((token === import21.ViewUtils)) { return this._ViewUtils_30; }
    if ((token === import78.IterableDiffers)) { return this._IterableDiffers_31; }
    if ((token === import79.KeyValueDiffers)) { return this._KeyValueDiffers_32; }
    if ((token === import18.SharedStylesHost)) { return this._SharedStylesHost_33; }
    if ((token === import22.Title)) { return this._Title_34; }
    if ((token === import23.RadioControlRegistry)) { return this._RadioControlRegistry_35; }
    if ((token === import7.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_36; }
    if ((token === import60.LocationStrategy)) { return this._LocationStrategy_37; }
    if ((token === import24.Location)) { return this._Location_38; }
    if ((token === import25.UrlSerializer)) { return this._UrlSerializer_39; }
    if ((token === import26.RouterOutletMap)) { return this._RouterOutletMap_40; }
    if ((token === import80.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_41; }
    if ((token === import81.ROUTES)) { return this._ROUTES_42; }
    if ((token === import70.Router)) { return this._Router_43; }
    if ((token === import82.ActivatedRoute)) { return this._ActivatedRoute_44; }
    if ((token === import28.NoPreloading)) { return this._NoPreloading_45; }
    if ((token === import28.PreloadingStrategy)) { return this._PreloadingStrategy_46; }
    if ((token === import28.RouterPreloader)) { return this._RouterPreloader_47; }
    if ((token === import28.PreloadAllModules)) { return this._PreloadAllModules_48; }
    if ((token === import54.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_49; }
    if ((token === import29.Ng2ComponentFactory)) { return this._Ng2ComponentFactory_50; }
    if ((token === import83.BaseComponentFactory)) { return this._BaseComponentFactory_51; }
    if ((token === import30.Ng2FrameworkFactory)) { return this._Ng2FrameworkFactory_52; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__16.ngOnDestroy();
    this._RouterPreloader_47.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);