/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../app/clickable.parent.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './clickable.component.ngfactory';
import * as import11 from '../../app/clickable.component';
export class Wrapper_ClickableParentComponent {
  context:import0.ClickableParentComponent;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.ClickableParentComponent();
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_ClickableParentComponent_Host:import2.RenderComponentType = (null as any);
class _View_ClickableParentComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ClickableParentComponent_0_4:Wrapper_ClickableParentComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ClickableParentComponent_Host0,renderType_ClickableParentComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'clickable-cell',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ClickableParentComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ClickableParentComponent_0_4 = new Wrapper_ClickableParentComponent();
    this._appEl_0.initComponent(this._ClickableParentComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._ClickableParentComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ClickableParentComponent) && (0 === requestNodeIndex))) { return this._ClickableParentComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ClickableParentComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._ClickableParentComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ClickableParentComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ClickableParentComponent_Host === (null as any))) { (renderType_ClickableParentComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ClickableParentComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ClickableParentComponentNgFactory:import9.ComponentFactory<import0.ClickableParentComponent> = new import9.ComponentFactory<import0.ClickableParentComponent>('clickable-cell',viewFactory_ClickableParentComponent_Host0,import0.ClickableParentComponent);
const styles_ClickableParentComponent:any[] = ([] as any[]);
var renderType_ClickableParentComponent:import2.RenderComponentType = (null as any);
class _View_ClickableParentComponent0 extends import1.AppView<import0.ClickableParentComponent> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import3.AppElement;
  _ClickableComponent_1_4:import10.Wrapper_ClickableComponent;
  _text_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ClickableParentComponent0,renderType_ClickableParentComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = import4.createRenderElement(this.renderer,parentRenderNode,'ag-clickable',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_1 = new import3.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import10.viewFactory_ClickableComponent0(this.viewUtils,this.injector(1),this._appEl_1);
    this._ClickableComponent_1_4 = new import10.Wrapper_ClickableComponent();
    this._appEl_1.initComponent(this._ClickableComponent_1_4.context,([] as any[]),compView_1);
    compView_1.create(this._ClickableComponent_1_4.context,([] as any[]),(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_1,'onClicked',this.eventHandler(this._handle_onClicked_1_0.bind(this)));
    const subscription_0:any = this._ClickableComponent_1_4.context.onClicked.subscribe(this.eventHandler(this._handle_onClicked_1_0.bind(this)));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2
    ]
    ,[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.ClickableComponent) && (1 === requestNodeIndex))) { return this._ClickableComponent_1_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1_0_0:any = this.context.cell;
    this._ClickableComponent_1_4.check_cell(currVal_1_0_0,throwOnChange,false);
    this._ClickableComponent_1_4.detectChangesInInputProps(this,this._el_1,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._ClickableComponent_1_4.detectChangesInHostProps(this,this._el_1,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_onClicked_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_1_0:any = ((<any>this.context.clicked($event)) !== false);
    return (true && pd_1_0);
  }
}
export function viewFactory_ClickableParentComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.ClickableParentComponent> {
  if ((renderType_ClickableParentComponent === (null as any))) { (renderType_ClickableParentComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,styles_ClickableParentComponent,{})); }
  return new _View_ClickableParentComponent0(viewUtils,parentInjector,declarationEl);
}