/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../app/clickable.module';
import * as import2 from '@angular/core/src/di/injector';
class ClickableModuleInjector extends import0.NgModuleInjector<import1.ClickableModule> {
  _ClickableModule_0:import1.ClickableModule;
  constructor(parent:import2.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.ClickableModule {
    this._ClickableModule_0 = new import1.ClickableModule();
    return this._ClickableModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.ClickableModule)) { return this._ClickableModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ClickableModuleNgFactory:import0.NgModuleFactory<import1.ClickableModule> = new import0.NgModuleFactory(ClickableModuleInjector,import1.ClickableModule);