/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../app/clickable.parent.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../app/clickable.component';
import * as import9 from './clickable.component.ngfactory';
export class Wrapper_ClickableParentComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ClickableParentComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.ClickableParentComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ClickableParentComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_ClickableParentComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.ClickableParentComponent>;
  _ClickableParentComponent_0_3:Wrapper_ClickableParentComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ClickableParentComponent_Host0,renderType_ClickableParentComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'clickable-cell',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ClickableParentComponent0(this.viewUtils,this,0,this._el_0);
    this._ClickableParentComponent_0_3 = new Wrapper_ClickableParentComponent();
    this.compView_0.create(this._ClickableParentComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._ClickableParentComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ClickableParentComponent) && (0 === requestNodeIndex))) { return this._ClickableParentComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ClickableParentComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ClickableParentComponentNgFactory:import7.ComponentFactory<import0.ClickableParentComponent> = new import7.ComponentFactory<import0.ClickableParentComponent>('clickable-cell',View_ClickableParentComponent_Host0,import0.ClickableParentComponent);
const styles_ClickableParentComponent:any[] = ([] as any[]);
var renderType_ClickableParentComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_ClickableParentComponent,{});
export class View_ClickableParentComponent0 extends import1.AppView<import0.ClickableParentComponent> {
  _text_0:any;
  _el_1:any;
  compView_1:import1.AppView<import8.ClickableComponent>;
  _ClickableComponent_1_3:import9.Wrapper_ClickableComponent;
  _text_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ClickableParentComponent0,renderType_ClickableParentComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'ag-clickable',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_1 = new import9.View_ClickableComponent0(this.viewUtils,this,1,this._el_1);
    this._ClickableComponent_1_3 = new import9.Wrapper_ClickableComponent();
    this.compView_1.create(this._ClickableComponent_1_3.context);
    this._text_2 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_1,new import3.InlineArray2(2,'onClicked',(null as any)),this.eventHandler(this.handleEvent_1));
    this._ClickableComponent_1_3.subscribe(this,this.eventHandler(this.handleEvent_1),true);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import8.ClickableComponent) && (1 === requestNodeIndex))) { return this._ClickableComponent_1_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1_0_0:any = this.context.cell;
    this._ClickableComponent_1_3.check_cell(currVal_1_0_0,throwOnChange,false);
    this._ClickableComponent_1_3.ngDoCheck(this,this._el_1,throwOnChange);
    this.compView_1.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_1.destroy();
    this._ClickableComponent_1_3.ngOnDestroy();
  }
  handleEvent_1(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onClicked')) {
      const pd_sub_0:any = ((<any>this.context.clicked($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}