/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../app/filter-component.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/core/src/linker/view_container';
import * as import9 from 'ag-grid-ng2/lib/agGridNg2';
import * as import10 from '../node_modules/ag-grid-ng2/lib/agGridNg2.ngfactory';
import * as import11 from '@angular/core/src/linker/query_list';
import * as import12 from '@angular/core/src/linker/element_ref';
import * as import13 from 'ag-grid-ng2/lib/ng2FrameworkFactory';
export class Wrapper_FilterComponentComponent {
  /*private*/ _eventHandler:Function;
  context:import0.FilterComponentComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.FilterComponentComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_FilterComponentComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_FilterComponentComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.FilterComponentComponent>;
  _FilterComponentComponent_0_3:Wrapper_FilterComponentComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_FilterComponentComponent_Host0,renderType_FilterComponentComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ag-filter-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_FilterComponentComponent0(this.viewUtils,this,0,this._el_0);
    this._FilterComponentComponent_0_3 = new Wrapper_FilterComponentComponent();
    this.compView_0.create(this._FilterComponentComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._FilterComponentComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.FilterComponentComponent) && (0 === requestNodeIndex))) { return this._FilterComponentComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._FilterComponentComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const FilterComponentComponentNgFactory:import7.ComponentFactory<import0.FilterComponentComponent> = new import7.ComponentFactory<import0.FilterComponentComponent>('ag-filter-component',View_FilterComponentComponent_Host0,import0.FilterComponentComponent);
const styles_FilterComponentComponent:any[] = ([] as any[]);
var renderType_FilterComponentComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_FilterComponentComponent,{});
export class View_FilterComponentComponent0 extends import1.AppView<import0.FilterComponentComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  /*private*/ _vc_8:import8.ViewContainer;
  compView_8:import1.AppView<import9.AgGridNg2>;
  _AgGridNg2_8_5:import10.Wrapper_AgGridNg2;
  _query_AgGridColumn_8_0:import11.QueryList<any>;
  _text_9:any;
  _text_10:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_FilterComponentComponent0,renderType_FilterComponentComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'style','width: 800px;'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'h2',new import3.InlineArray2(2,'style','margin-bottom:5px'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'With Filters Components',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'button',new import3.InlineArray2(2,'style','margin-bottom: 10px'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'Filter Instance Method',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_0,'ag-grid-ng2',new import3.InlineArray4(4,'class','ag-fresh','style','width: 100%; height: 350px;'),(null as any));
    this._vc_8 = new import8.ViewContainer(8,0,this,this._el_8);
    this.compView_8 = new import10.View_AgGridNg20(this.viewUtils,this,8,this._el_8);
    this._AgGridNg2_8_5 = new import10.Wrapper_AgGridNg2(new import12.ElementRef(this._el_8),this._vc_8.vcRef,this.parentView.injectorGet(import13.Ng2FrameworkFactory,this.parentIndex));
    this._query_AgGridColumn_8_0 = new import11.QueryList<any>();
    this._text_9 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_8.create(this._AgGridNg2_8_5.context);
    this._text_10 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_5,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_5));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import9.AgGridNg2) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._AgGridNg2_8_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_8_0_0:any = this.context.gridOptions;
    this._AgGridNg2_8_5.check_gridOptions(currVal_8_0_0,throwOnChange,false);
    this._AgGridNg2_8_5.ngDoCheck(this,this._el_8,throwOnChange);
    this._vc_8.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) { if (this._query_AgGridColumn_8_0.dirty) {
      this._query_AgGridColumn_8_0.reset(([] as any[]));
      this._AgGridNg2_8_5.context.columns = this._query_AgGridColumn_8_0;
      this._query_AgGridColumn_8_0.notifyOnChanges();
    } }
    this.compView_8.detectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._AgGridNg2_8_5.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._vc_8.destroyNestedViews();
    this.compView_8.destroy();
    this._AgGridNg2_8_5.ngOnDestroy();
  }
  handleEvent_5(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.onClicked($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}