/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../app/mood-renderer.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/core/src/security';
export class Wrapper_MoodRendererComponent {
  context:import0.MoodRendererComponent;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.MoodRendererComponent();
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_MoodRendererComponent_Host:import2.RenderComponentType = (null as any);
class _View_MoodRendererComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _MoodRendererComponent_0_4:Wrapper_MoodRendererComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MoodRendererComponent_Host0,renderType_MoodRendererComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'mood-cell',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_MoodRendererComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._MoodRendererComponent_0_4 = new Wrapper_MoodRendererComponent();
    this._appEl_0.initComponent(this._MoodRendererComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._MoodRendererComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.MoodRendererComponent) && (0 === requestNodeIndex))) { return this._MoodRendererComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MoodRendererComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._MoodRendererComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MoodRendererComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_MoodRendererComponent_Host === (null as any))) { (renderType_MoodRendererComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_MoodRendererComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const MoodRendererComponentNgFactory:import9.ComponentFactory<import0.MoodRendererComponent> = new import9.ComponentFactory<import0.MoodRendererComponent>('mood-cell',viewFactory_MoodRendererComponent_Host0,import0.MoodRendererComponent);
const styles_MoodRendererComponent:any[] = ([] as any[]);
var renderType_MoodRendererComponent:import2.RenderComponentType = (null as any);
class _View_MoodRendererComponent0 extends import1.AppView<import0.MoodRendererComponent> {
  _el_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MoodRendererComponent0,renderType_MoodRendererComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_1 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'img',new import4.InlineArray2(2,'width','20px'),(null as any));
    this.init(([] as any[]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this.context.imgForMood;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import10.SecurityContext.URL,currVal_1));
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_MoodRendererComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.MoodRendererComponent> {
  if ((renderType_MoodRendererComponent === (null as any))) { (renderType_MoodRendererComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,styles_MoodRendererComponent,{})); }
  return new _View_MoodRendererComponent0(viewUtils,parentInjector,declarationEl);
}