/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../app/name-age-renderer.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
export class Wrapper_NameAndAgeRendererComponent {
  context:import0.NameAndAgeRendererComponent;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.NameAndAgeRendererComponent();
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_NameAndAgeRendererComponent_Host:import2.RenderComponentType = (null as any);
class _View_NameAndAgeRendererComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _NameAndAgeRendererComponent_0_4:Wrapper_NameAndAgeRendererComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_NameAndAgeRendererComponent_Host0,renderType_NameAndAgeRendererComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'full-width-cell',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_NameAndAgeRendererComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._NameAndAgeRendererComponent_0_4 = new Wrapper_NameAndAgeRendererComponent();
    this._appEl_0.initComponent(this._NameAndAgeRendererComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._NameAndAgeRendererComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.NameAndAgeRendererComponent) && (0 === requestNodeIndex))) { return this._NameAndAgeRendererComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NameAndAgeRendererComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._NameAndAgeRendererComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_NameAndAgeRendererComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_NameAndAgeRendererComponent_Host === (null as any))) { (renderType_NameAndAgeRendererComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_NameAndAgeRendererComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const NameAndAgeRendererComponentNgFactory:import9.ComponentFactory<import0.NameAndAgeRendererComponent> = new import9.ComponentFactory<import0.NameAndAgeRendererComponent>('full-width-cell',viewFactory_NameAndAgeRendererComponent_Host0,import0.NameAndAgeRendererComponent);
const styles_NameAndAgeRendererComponent:any[] = ([] as any[]);
var renderType_NameAndAgeRendererComponent:import2.RenderComponentType = (null as any);
class _View_NameAndAgeRendererComponent0 extends import1.AppView<import0.NameAndAgeRendererComponent> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_NameAndAgeRendererComponent0,renderType_NameAndAgeRendererComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_2 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'span',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = import4.interpolate(1,'Full Width Column! ',this.context.values,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_NameAndAgeRendererComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.NameAndAgeRendererComponent> {
  if ((renderType_NameAndAgeRendererComponent === (null as any))) { (renderType_NameAndAgeRendererComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,styles_NameAndAgeRendererComponent,{})); }
  return new _View_NameAndAgeRendererComponent0(viewUtils,parentInjector,declarationEl);
}