/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../app/params.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
export class Wrapper_ParamsComponent {
  context:import0.ParamsComponent;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.ParamsComponent();
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_ParamsComponent_Host:import2.RenderComponentType = (null as any);
class _View_ParamsComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ParamsComponent_0_4:Wrapper_ParamsComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ParamsComponent_Host0,renderType_ParamsComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'params-cell',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ParamsComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ParamsComponent_0_4 = new Wrapper_ParamsComponent();
    this._appEl_0.initComponent(this._ParamsComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._ParamsComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ParamsComponent) && (0 === requestNodeIndex))) { return this._ParamsComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ParamsComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._ParamsComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ParamsComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ParamsComponent_Host === (null as any))) { (renderType_ParamsComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ParamsComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ParamsComponentNgFactory:import9.ComponentFactory<import0.ParamsComponent> = new import9.ComponentFactory<import0.ParamsComponent>('params-cell',viewFactory_ParamsComponent_Host0,import0.ParamsComponent);
const styles_ParamsComponent:any[] = ([] as any[]);
var renderType_ParamsComponent:import2.RenderComponentType = (null as any);
class _View_ParamsComponent0 extends import1.AppView<import0.ParamsComponent> {
  _text_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ParamsComponent0,renderType_ParamsComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_1 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'',(null as any));
    this.init(([] as any[]),[this._text_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = import4.interpolate(2,'Field: ',this.context.params.colDef.field,', Value: ',this.context.params.value,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_0,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_ParamsComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.ParamsComponent> {
  if ((renderType_ParamsComponent === (null as any))) { (renderType_ParamsComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,styles_ParamsComponent,{})); }
  return new _View_ParamsComponent0(viewUtils,parentInjector,declarationEl);
}