/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../app/partial-match-filter.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/core/src/linker/query_list';
import * as import9 from '@angular/core/src/linker/view_container';
import * as import10 from '../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import11 from '../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import12 from '../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import13 from '@angular/core/src/linker/element_ref';
import * as import14 from '@angular/forms/src/directives/default_value_accessor';
import * as import15 from '@angular/forms/src/directives/control_value_accessor';
import * as import16 from '@angular/forms/src/directives/ng_model';
import * as import17 from '@angular/forms/src/directives/ng_control';
import * as import18 from '@angular/forms/src/directives/ng_control_status';
export class Wrapper_PartialMatchFilterComponent {
  /*private*/ _eventHandler:Function;
  context:import0.PartialMatchFilterComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.PartialMatchFilterComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_PartialMatchFilterComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_PartialMatchFilterComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.PartialMatchFilterComponent>;
  _PartialMatchFilterComponent_0_3:Wrapper_PartialMatchFilterComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PartialMatchFilterComponent_Host0,renderType_PartialMatchFilterComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'filter-cell',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_PartialMatchFilterComponent0(this.viewUtils,this,0,this._el_0);
    this._PartialMatchFilterComponent_0_3 = new Wrapper_PartialMatchFilterComponent();
    this.compView_0.create(this._PartialMatchFilterComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._PartialMatchFilterComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.PartialMatchFilterComponent) && (0 === requestNodeIndex))) { return this._PartialMatchFilterComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._PartialMatchFilterComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const PartialMatchFilterComponentNgFactory:import7.ComponentFactory<import0.PartialMatchFilterComponent> = new import7.ComponentFactory<import0.PartialMatchFilterComponent>('filter-cell',View_PartialMatchFilterComponent_Host0,import0.PartialMatchFilterComponent);
const styles_PartialMatchFilterComponent:any[] = ([] as any[]);
var renderType_PartialMatchFilterComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_PartialMatchFilterComponent,{});
export class View_PartialMatchFilterComponent0 extends import1.AppView<import0.PartialMatchFilterComponent> {
  _viewQuery_input_0:import8.QueryList<any>;
  _text_0:any;
  _el_1:any;
  /*private*/ _vc_1:import9.ViewContainer;
  _DefaultValueAccessor_1_5:import10.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_1_6:any[];
  _NgModel_1_7:import11.Wrapper_NgModel;
  _NgControl_1_8:any;
  _NgControlStatus_1_9:import12.Wrapper_NgControlStatus;
  _text_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PartialMatchFilterComponent0,renderType_PartialMatchFilterComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._viewQuery_input_0 = new import8.QueryList<any>();
    this._text_0 = this.renderer.createText(parentRenderNode,'\n        Filter: ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'input',new import3.InlineArray2(2,'style','height: 10px'),(null as any));
    this._vc_1 = new import9.ViewContainer(1,(null as any),this,this._el_1);
    this._DefaultValueAccessor_1_5 = new import10.Wrapper_DefaultValueAccessor(this.renderer,new import13.ElementRef(this._el_1));
    this._NG_VALUE_ACCESSOR_1_6 = [this._DefaultValueAccessor_1_5.context];
    this._NgModel_1_7 = new import11.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_1_6);
    this._NgControl_1_8 = this._NgModel_1_7.context;
    this._NgControlStatus_1_9 = new import12.Wrapper_NgControlStatus(this._NgControl_1_8);
    this._text_2 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_1,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_1));
    this._NgModel_1_7.subscribe(this,this.eventHandler(this.handleEvent_1),true);
    this._viewQuery_input_0.reset([this._vc_1.vcRef]);
    this.context.input = this._viewQuery_input_0.first;
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.DefaultValueAccessor) && (1 === requestNodeIndex))) { return this._DefaultValueAccessor_1_5.context; }
    if (((token === import15.NG_VALUE_ACCESSOR) && (1 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_1_6; }
    if (((token === import16.NgModel) && (1 === requestNodeIndex))) { return this._NgModel_1_7.context; }
    if (((token === import17.NgControl) && (1 === requestNodeIndex))) { return this._NgControl_1_8; }
    if (((token === import18.NgControlStatus) && (1 === requestNodeIndex))) { return this._NgControlStatus_1_9.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DefaultValueAccessor_1_5.ngDoCheck(this,this._el_1,throwOnChange);
    const currVal_1_1_0:any = this.context.text;
    this._NgModel_1_7.check_model(currVal_1_1_0,throwOnChange,false);
    this._NgModel_1_7.ngDoCheck(this,this._el_1,throwOnChange);
    this._NgControlStatus_1_9.ngDoCheck(this,this._el_1,throwOnChange);
    this._vc_1.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatus_1_9.checkHost(this,this,this._el_1,throwOnChange);
  }
  destroyInternal():void {
    this._vc_1.destroyNestedViews();
    this._NgModel_1_7.ngOnDestroy();
  }
  handleEvent_1(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_1_5.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>this.context.onChange($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}