/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../app/ratio.module';
import * as import2 from '@angular/core/src/di/injector';
class RatioModuleInjector extends import0.NgModuleInjector<import1.RatioModule> {
  _RatioModule_0:import1.RatioModule;
  constructor(parent:import2.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.RatioModule {
    this._RatioModule_0 = new import1.RatioModule();
    return this._RatioModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.RatioModule)) { return this._RatioModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const RatioModuleNgFactory:import0.NgModuleFactory<import1.RatioModule> = new import0.NgModuleFactory(RatioModuleInjector,import1.RatioModule);