/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../app/ratio.parent.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './ratio.component.ngfactory';
import * as import11 from '../../app/ratio.component';
export class Wrapper_RatioParentComponent {
  context:import0.RatioParentComponent;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.RatioParentComponent();
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_RatioParentComponent_Host:import2.RenderComponentType = (null as any);
class _View_RatioParentComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _RatioParentComponent_0_4:Wrapper_RatioParentComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_RatioParentComponent_Host0,renderType_RatioParentComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'ratio-cell',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_RatioParentComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._RatioParentComponent_0_4 = new Wrapper_RatioParentComponent();
    this._appEl_0.initComponent(this._RatioParentComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._RatioParentComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.RatioParentComponent) && (0 === requestNodeIndex))) { return this._RatioParentComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._RatioParentComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._RatioParentComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_RatioParentComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_RatioParentComponent_Host === (null as any))) { (renderType_RatioParentComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_RatioParentComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const RatioParentComponentNgFactory:import9.ComponentFactory<import0.RatioParentComponent> = new import9.ComponentFactory<import0.RatioParentComponent>('ratio-cell',viewFactory_RatioParentComponent_Host0,import0.RatioParentComponent);
const styles_RatioParentComponent:any[] = ['ag-ratio[_ngcontent-%COMP%] {\n          display: block;\n          overflow:hidden;\n          border:1px solid #ccc;\n          border-radius:6px;\n          background: #fff;\n        }'];
var renderType_RatioParentComponent:import2.RenderComponentType = (null as any);
class _View_RatioParentComponent0 extends import1.AppView<import0.RatioParentComponent> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import3.AppElement;
  _RatioComponent_1_4:import10.Wrapper_RatioComponent;
  _text_2:any;
  _text_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_RatioParentComponent0,renderType_RatioParentComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = import4.createRenderElement(this.renderer,parentRenderNode,'ag-ratio',new import4.InlineArray2(2,'style','height:20px'),(null as any));
    this._appEl_1 = new import3.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import10.viewFactory_RatioComponent0(this.viewUtils,this.injector(1),this._appEl_1);
    this._RatioComponent_1_4 = new import10.Wrapper_RatioComponent();
    this._appEl_1.initComponent(this._RatioComponent_1_4.context,([] as any[]),compView_1);
    this._text_2 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_1.create(this._RatioComponent_1_4.context,([] as any[]),(null as any));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.RatioComponent) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._RatioComponent_1_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1_0_0:any = ((this.context.params == (null as any))? (null as any): ((this.context.params.value == (null as any))? (null as any): this.context.params.value.top));
    this._RatioComponent_1_4.check_topRatio(currVal_1_0_0,throwOnChange,false);
    const currVal_1_0_1:any = ((this.context.params == (null as any))? (null as any): ((this.context.params.value == (null as any))? (null as any): this.context.params.value.bottom));
    this._RatioComponent_1_4.check_bottomRatio(currVal_1_0_1,throwOnChange,false);
    this._RatioComponent_1_4.detectChangesInInputProps(this,this._el_1,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._RatioComponent_1_4.detectChangesInHostProps(this,this._el_1,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_RatioParentComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.RatioParentComponent> {
  if ((renderType_RatioParentComponent === (null as any))) { (renderType_RatioParentComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.Emulated,styles_RatioParentComponent,{})); }
  return new _View_RatioParentComponent0(viewUtils,parentInjector,declarationEl);
}