/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../app/rich-grid-declarative.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import11 from '@angular/core/src/linker/template_ref';
import * as import12 from '@angular/common/src/directives/ng_if';
import * as import13 from '../node_modules/ag-grid-ng2/dist/agGridNg2.ngfactory';
import * as import14 from '@angular/core/src/linker/query_list';
import * as import15 from '../node_modules/ag-grid-ng2/dist/agGridColumn.ngfactory';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from 'ag-grid-ng2/dist/ng2FrameworkFactory';
import * as import18 from 'ag-grid-ng2/dist/agGridColumn';
import * as import19 from 'ag-grid-ng2/dist/agGridNg2';
export class Wrapper_RichGridDeclarativeComponent {
  context:import0.RichGridDeclarativeComponent;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.RichGridDeclarativeComponent();
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_RichGridDeclarativeComponent_Host:import2.RenderComponentType = (null as any);
class _View_RichGridDeclarativeComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _RichGridDeclarativeComponent_0_4:Wrapper_RichGridDeclarativeComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_RichGridDeclarativeComponent_Host0,renderType_RichGridDeclarativeComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'ag-rich-grid-declarative',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_RichGridDeclarativeComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._RichGridDeclarativeComponent_0_4 = new Wrapper_RichGridDeclarativeComponent();
    this._appEl_0.initComponent(this._RichGridDeclarativeComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._RichGridDeclarativeComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.RichGridDeclarativeComponent) && (0 === requestNodeIndex))) { return this._RichGridDeclarativeComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._RichGridDeclarativeComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._RichGridDeclarativeComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_RichGridDeclarativeComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_RichGridDeclarativeComponent_Host === (null as any))) { (renderType_RichGridDeclarativeComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_RichGridDeclarativeComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const RichGridDeclarativeComponentNgFactory:import9.ComponentFactory<import0.RichGridDeclarativeComponent> = new import9.ComponentFactory<import0.RichGridDeclarativeComponent>('ag-rich-grid-declarative',viewFactory_RichGridDeclarativeComponent_Host0,import0.RichGridDeclarativeComponent);
const styles_RichGridDeclarativeComponent:any[] = ['.toolbar[_ngcontent-%COMP%]   button[_ngcontent-%COMP%] {margin: 2px; padding: 0;}'];
var renderType_RichGridDeclarativeComponent:import2.RenderComponentType = (null as any);
class _View_RichGridDeclarativeComponent0 extends import1.AppView<import0.RichGridDeclarativeComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _anchor_27:any;
  /*private*/ _appEl_27:import3.AppElement;
  _TemplateRef_27_5:any;
  _NgIf_27_6:import10.Wrapper_NgIf;
  _text_28:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_RichGridDeclarativeComponent0,renderType_RichGridDeclarativeComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArray2(2,'style','width: 800px;'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'h1',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Rich Grid with Declarative Markup',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_5 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'style','padding: 4px;'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_7 = import4.createRenderElement(this.renderer,this._el_5,'div',new import4.InlineArray2(2,'style','float: right;'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_9 = import4.createRenderElement(this.renderer,this._el_7,'input',new import4.InlineArray8(6,'id','quickFilterInput','placeholder','Type text to filter...','type','text'),(null as any));
    this._text_10 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_11 = import4.createRenderElement(this.renderer,this._el_7,'button',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'Destroy Grid',(null as any));
    this._text_13 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_14 = import4.createRenderElement(this.renderer,this._el_7,'button',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'Create Grid',(null as any));
    this._text_16 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._text_17 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_18 = import4.createRenderElement(this.renderer,this._el_5,'div',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'\n            ',(null as any));
    this._el_20 = import4.createRenderElement(this.renderer,this._el_18,'b',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'Employees Skills and Contact Details',(null as any));
    this._text_22 = this.renderer.createText(this._el_18,'',(null as any));
    this._text_23 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_24 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_25 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'style','clear: both;'),(null as any));
    this._text_26 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._anchor_27 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_27 = new import3.AppElement(27,0,this,this._anchor_27);
    this._TemplateRef_27_5 = new import11.TemplateRef_(this._appEl_27,viewFactory_RichGridDeclarativeComponent1);
    this._NgIf_27_6 = new import10.Wrapper_NgIf(this._appEl_27.vcRef,this._TemplateRef_27_5);
    this._text_28 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_9,'keyup',this.eventHandler(this._handle_keyup_9_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_11,'click',this.eventHandler(this._handle_click_11_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_14,'click',this.eventHandler(this._handle_click_14_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._anchor_27,
      this._text_28
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.TemplateRef) && (27 === requestNodeIndex))) { return this._TemplateRef_27_5; }
    if (((token === import12.NgIf) && (27 === requestNodeIndex))) { return this._NgIf_27_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_27_0_0:any = this.context.showGrid;
    this._NgIf_27_6.check_ngIf(currVal_27_0_0,throwOnChange,false);
    this._NgIf_27_6.detectChangesInInputProps(this,this._anchor_27,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_32:boolean = !this.context.showGrid;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementProperty(this._el_11,'disabled',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this.context.showGrid;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementProperty(this._el_14,'disabled',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = import4.interpolate(1,'\n            ',this.context.rowCount,'\n        ');
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setText(this._text_22,currVal_34);
      this._expr_34 = currVal_34;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_keyup_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_9_0:any = ((<any>this.context.onQuickFilterChanged($event)) !== false);
    return (true && pd_9_0);
  }
  private _handle_click_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_11_0:any = ((<any>(this.context.showGrid = false)) !== false);
    return (true && pd_11_0);
  }
  private _handle_click_14_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_14_0:any = ((<any>(this.context.showGrid = true)) !== false);
    return (true && pd_14_0);
  }
}
export function viewFactory_RichGridDeclarativeComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.RichGridDeclarativeComponent> {
  if ((renderType_RichGridDeclarativeComponent === (null as any))) { (renderType_RichGridDeclarativeComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.Emulated,styles_RichGridDeclarativeComponent,{})); }
  return new _View_RichGridDeclarativeComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_RichGridDeclarativeComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  /*private*/ _appEl_39:import3.AppElement;
  _AgGridNg2_39_5:import13.Wrapper_AgGridNg2;
  _query_AgGridColumn_39_0:import14.QueryList<any>;
  _text_40:any;
  _el_41:any;
  /*private*/ _appEl_41:import3.AppElement;
  _AgGridColumn_41_4:import15.Wrapper_AgGridColumn;
  _query_AgGridColumn_41_0:import14.QueryList<any>;
  _text_42:any;
  _el_43:any;
  /*private*/ _appEl_43:import3.AppElement;
  _AgGridColumn_43_4:import15.Wrapper_AgGridColumn;
  _query_AgGridColumn_43_0:import14.QueryList<any>;
  _text_44:any;
  _el_45:any;
  /*private*/ _appEl_45:import3.AppElement;
  _AgGridColumn_45_4:import15.Wrapper_AgGridColumn;
  _query_AgGridColumn_45_0:import14.QueryList<any>;
  _text_46:any;
  _el_47:any;
  /*private*/ _appEl_47:import3.AppElement;
  _AgGridColumn_47_4:import15.Wrapper_AgGridColumn;
  _query_AgGridColumn_47_0:import14.QueryList<any>;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  /*private*/ _appEl_50:import3.AppElement;
  _AgGridColumn_50_4:import15.Wrapper_AgGridColumn;
  _query_AgGridColumn_50_0:import14.QueryList<any>;
  _text_51:any;
  _el_52:any;
  /*private*/ _appEl_52:import3.AppElement;
  _AgGridColumn_52_4:import15.Wrapper_AgGridColumn;
  _query_AgGridColumn_52_0:import14.QueryList<any>;
  _text_53:any;
  _el_54:any;
  /*private*/ _appEl_54:import3.AppElement;
  _AgGridColumn_54_4:import15.Wrapper_AgGridColumn;
  _query_AgGridColumn_54_0:import14.QueryList<any>;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  /*private*/ _appEl_57:import3.AppElement;
  _AgGridColumn_57_4:import15.Wrapper_AgGridColumn;
  _query_AgGridColumn_57_0:import14.QueryList<any>;
  _text_58:any;
  _el_59:any;
  /*private*/ _appEl_59:import3.AppElement;
  _AgGridColumn_59_4:import15.Wrapper_AgGridColumn;
  _query_AgGridColumn_59_0:import14.QueryList<any>;
  _text_60:any;
  _el_61:any;
  /*private*/ _appEl_61:import3.AppElement;
  _AgGridColumn_61_4:import15.Wrapper_AgGridColumn;
  _query_AgGridColumn_61_0:import14.QueryList<any>;
  _text_62:any;
  _el_63:any;
  /*private*/ _appEl_63:import3.AppElement;
  _AgGridColumn_63_4:import15.Wrapper_AgGridColumn;
  _query_AgGridColumn_63_0:import14.QueryList<any>;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_RichGridDeclarativeComponent1,renderType_RichGridDeclarativeComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'div',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n        ',(null as any));
    this._text_2 = this.renderer.createText(this._el_0,'\n\n        ',(null as any));
    this._el_3 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray4(4,'class','toolbar','style','padding: 4px;'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n            ',(null as any));
    this._el_5 = import4.createRenderElement(this.renderer,this._el_3,'span',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n                Grid API:\n                ',(null as any));
    this._el_7 = import4.createRenderElement(this.renderer,this._el_5,'button',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'Select All',(null as any));
    this._text_9 = this.renderer.createText(this._el_5,'\n                ',(null as any));
    this._el_10 = import4.createRenderElement(this.renderer,this._el_5,'button',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'Clear Selection',(null as any));
    this._text_12 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._text_13 = this.renderer.createText(this._el_3,'\n            ',(null as any));
    this._el_14 = import4.createRenderElement(this.renderer,this._el_3,'span',new import4.InlineArray2(2,'style','margin-left: 20px;'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n                Column API:\n                ',(null as any));
    this._el_16 = import4.createRenderElement(this.renderer,this._el_14,'button',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'Hide Country Column',(null as any));
    this._text_18 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._el_19 = import4.createRenderElement(this.renderer,this._el_14,'button',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'Show Country Column',(null as any));
    this._text_21 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._text_22 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._text_23 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_24 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'style','clear: both;'),(null as any));
    this._text_25 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_26 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray4(4,'class','toolbar','style','padding: 4px;'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n            ',(null as any));
    this._el_28 = import4.createRenderElement(this.renderer,this._el_26,'label',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'\n                ',(null as any));
    this._el_30 = import4.createRenderElement(this.renderer,this._el_28,'input',new import4.InlineArray2(2,'type','checkbox'),(null as any));
    this._text_31 = this.renderer.createText(this._el_28,'\n                Show Tool Panel\n            ',(null as any));
    this._text_32 = this.renderer.createText(this._el_26,'\n            ',(null as any));
    this._el_33 = import4.createRenderElement(this.renderer,this._el_26,'button',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'Refresh Data',(null as any));
    this._text_35 = this.renderer.createText(this._el_26,'\n        ',(null as any));
    this._text_36 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_37 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'style','clear: both;'),(null as any));
    this._text_38 = this.renderer.createText(this._el_0,'\n\n        ',(null as any));
    this._el_39 = import4.createRenderElement(this.renderer,this._el_0,'ag-grid-ng2',new import4.InlineArrayDynamic(22,'class','ag-fresh','enableColResize','','enableFilter','','enableSorting','','groupHeaders','','rowHeight','22','rowSelection','multiple','style','width: 100%; height: 350px;','suppressRowClickSelection','','toolPanelSuppressGroups','','toolPanelSuppressValues',''),(null as any));
    this._appEl_39 = new import3.AppElement(39,0,this,this._el_39);
    var compView_39:any = import13.viewFactory_AgGridNg20(this.viewUtils,this.injector(39),this._appEl_39);
    this._AgGridNg2_39_5 = new import13.Wrapper_AgGridNg2(new import16.ElementRef(this._el_39),this._appEl_39.vcRef,this.parent.parentInjector.get(import17.Ng2FrameworkFactory));
    this._query_AgGridColumn_39_0 = new import14.QueryList<any>();
    this._appEl_39.initComponent(this._AgGridNg2_39_5.context,([] as any[]),compView_39);
    this._text_40 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_41 = import4.createRenderElement(this.renderer,(null as any),'ag-grid-column',new import4.InlineArray2(2,'headerName','Employee'),(null as any));
    this._appEl_41 = new import3.AppElement(41,39,this,this._el_41);
    var compView_41:any = import15.viewFactory_AgGridColumn0(this.viewUtils,this.injector(41),this._appEl_41);
    this._AgGridColumn_41_4 = new import15.Wrapper_AgGridColumn();
    this._query_AgGridColumn_41_0 = new import14.QueryList<any>();
    this._appEl_41.initComponent(this._AgGridColumn_41_4.context,([] as any[]),compView_41);
    this._text_42 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_43 = import4.createRenderElement(this.renderer,(null as any),'ag-grid-column',new import4.InlineArray2(2,'headerName','#'),(null as any));
    this._appEl_43 = new import3.AppElement(43,41,this,this._el_43);
    var compView_43:any = import15.viewFactory_AgGridColumn0(this.viewUtils,this.injector(43),this._appEl_43);
    this._AgGridColumn_43_4 = new import15.Wrapper_AgGridColumn();
    this._query_AgGridColumn_43_0 = new import14.QueryList<any>();
    this._appEl_43.initComponent(this._AgGridColumn_43_4.context,([] as any[]),compView_43);
    compView_43.create(this._AgGridColumn_43_4.context,([] as any[]),(null as any));
    this._text_44 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_45 = import4.createRenderElement(this.renderer,(null as any),'ag-grid-column',new import4.InlineArray4(4,'field','name','headerName','Name'),(null as any));
    this._appEl_45 = new import3.AppElement(45,41,this,this._el_45);
    var compView_45:any = import15.viewFactory_AgGridColumn0(this.viewUtils,this.injector(45),this._appEl_45);
    this._AgGridColumn_45_4 = new import15.Wrapper_AgGridColumn();
    this._query_AgGridColumn_45_0 = new import14.QueryList<any>();
    this._appEl_45.initComponent(this._AgGridColumn_45_4.context,([] as any[]),compView_45);
    compView_45.create(this._AgGridColumn_45_4.context,([] as any[]),(null as any));
    this._text_46 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_47 = import4.createRenderElement(this.renderer,(null as any),'ag-grid-column',new import4.InlineArray4(4,'field','country','headerName','Country'),(null as any));
    this._appEl_47 = new import3.AppElement(47,41,this,this._el_47);
    var compView_47:any = import15.viewFactory_AgGridColumn0(this.viewUtils,this.injector(47),this._appEl_47);
    this._AgGridColumn_47_4 = new import15.Wrapper_AgGridColumn();
    this._query_AgGridColumn_47_0 = new import14.QueryList<any>();
    this._appEl_47.initComponent(this._AgGridColumn_47_4.context,([] as any[]),compView_47);
    compView_47.create(this._AgGridColumn_47_4.context,([] as any[]),(null as any));
    this._text_48 = this.renderer.createText((null as any),'\n            ',(null as any));
    compView_41.create(this._AgGridColumn_41_4.context,([] as any[]),(null as any));
    this._text_49 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_50 = import4.createRenderElement(this.renderer,(null as any),'ag-grid-column',new import4.InlineArray2(2,'headerName','IT Skills'),(null as any));
    this._appEl_50 = new import3.AppElement(50,39,this,this._el_50);
    var compView_50:any = import15.viewFactory_AgGridColumn0(this.viewUtils,this.injector(50),this._appEl_50);
    this._AgGridColumn_50_4 = new import15.Wrapper_AgGridColumn();
    this._query_AgGridColumn_50_0 = new import14.QueryList<any>();
    this._appEl_50.initComponent(this._AgGridColumn_50_4.context,([] as any[]),compView_50);
    this._text_51 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_52 = import4.createRenderElement(this.renderer,(null as any),'ag-grid-column',new import4.InlineArray2(2,'headerName','Skills'),(null as any));
    this._appEl_52 = new import3.AppElement(52,50,this,this._el_52);
    var compView_52:any = import15.viewFactory_AgGridColumn0(this.viewUtils,this.injector(52),this._appEl_52);
    this._AgGridColumn_52_4 = new import15.Wrapper_AgGridColumn();
    this._query_AgGridColumn_52_0 = new import14.QueryList<any>();
    this._appEl_52.initComponent(this._AgGridColumn_52_4.context,([] as any[]),compView_52);
    compView_52.create(this._AgGridColumn_52_4.context,([] as any[]),(null as any));
    this._text_53 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_54 = import4.createRenderElement(this.renderer,(null as any),'ag-grid-column',new import4.InlineArray4(4,'field','proficiency','headerName','Proficiency'),(null as any));
    this._appEl_54 = new import3.AppElement(54,50,this,this._el_54);
    var compView_54:any = import15.viewFactory_AgGridColumn0(this.viewUtils,this.injector(54),this._appEl_54);
    this._AgGridColumn_54_4 = new import15.Wrapper_AgGridColumn();
    this._query_AgGridColumn_54_0 = new import14.QueryList<any>();
    this._appEl_54.initComponent(this._AgGridColumn_54_4.context,([] as any[]),compView_54);
    compView_54.create(this._AgGridColumn_54_4.context,([] as any[]),(null as any));
    this._text_55 = this.renderer.createText((null as any),'\n            ',(null as any));
    compView_50.create(this._AgGridColumn_50_4.context,([] as any[]),(null as any));
    this._text_56 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_57 = import4.createRenderElement(this.renderer,(null as any),'ag-grid-column',new import4.InlineArray2(2,'headerName','Contact'),(null as any));
    this._appEl_57 = new import3.AppElement(57,39,this,this._el_57);
    var compView_57:any = import15.viewFactory_AgGridColumn0(this.viewUtils,this.injector(57),this._appEl_57);
    this._AgGridColumn_57_4 = new import15.Wrapper_AgGridColumn();
    this._query_AgGridColumn_57_0 = new import14.QueryList<any>();
    this._appEl_57.initComponent(this._AgGridColumn_57_4.context,([] as any[]),compView_57);
    this._text_58 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_59 = import4.createRenderElement(this.renderer,(null as any),'ag-grid-column',new import4.InlineArray8(6,'field','mobile','filter','text','headerName','Mobile'),(null as any));
    this._appEl_59 = new import3.AppElement(59,57,this,this._el_59);
    var compView_59:any = import15.viewFactory_AgGridColumn0(this.viewUtils,this.injector(59),this._appEl_59);
    this._AgGridColumn_59_4 = new import15.Wrapper_AgGridColumn();
    this._query_AgGridColumn_59_0 = new import14.QueryList<any>();
    this._appEl_59.initComponent(this._AgGridColumn_59_4.context,([] as any[]),compView_59);
    compView_59.create(this._AgGridColumn_59_4.context,([] as any[]),(null as any));
    this._text_60 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_61 = import4.createRenderElement(this.renderer,(null as any),'ag-grid-column',new import4.InlineArray8(6,'field','landline','filter','text','headerName','Land-line'),(null as any));
    this._appEl_61 = new import3.AppElement(61,57,this,this._el_61);
    var compView_61:any = import15.viewFactory_AgGridColumn0(this.viewUtils,this.injector(61),this._appEl_61);
    this._AgGridColumn_61_4 = new import15.Wrapper_AgGridColumn();
    this._query_AgGridColumn_61_0 = new import14.QueryList<any>();
    this._appEl_61.initComponent(this._AgGridColumn_61_4.context,([] as any[]),compView_61);
    compView_61.create(this._AgGridColumn_61_4.context,([] as any[]),(null as any));
    this._text_62 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_63 = import4.createRenderElement(this.renderer,(null as any),'ag-grid-column',new import4.InlineArray8(6,'field','address','filter','text','headerName','Address'),(null as any));
    this._appEl_63 = new import3.AppElement(63,57,this,this._el_63);
    var compView_63:any = import15.viewFactory_AgGridColumn0(this.viewUtils,this.injector(63),this._appEl_63);
    this._AgGridColumn_63_4 = new import15.Wrapper_AgGridColumn();
    this._query_AgGridColumn_63_0 = new import14.QueryList<any>();
    this._appEl_63.initComponent(this._AgGridColumn_63_4.context,([] as any[]),compView_63);
    compView_63.create(this._AgGridColumn_63_4.context,([] as any[]),(null as any));
    this._text_64 = this.renderer.createText((null as any),'\n            ',(null as any));
    compView_57.create(this._AgGridColumn_57_4.context,([] as any[]),(null as any));
    this._text_65 = this.renderer.createText((null as any),'\n        ',(null as any));
    compView_39.create(this._AgGridNg2_39_5.context,([] as any[]),(null as any));
    this._text_66 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_7,'click',this.eventHandler(this._handle_click_7_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_10,'click',this.eventHandler(this._handle_click_10_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_16,'click',this.eventHandler(this._handle_click_16_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_19,'click',this.eventHandler(this._handle_click_19_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_30,'change',this.eventHandler(this._handle_change_30_0.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_33,'click',this.eventHandler(this._handle_click_33_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._text_66
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.AgGridColumn) && (43 === requestNodeIndex))) { return this._AgGridColumn_43_4.context; }
    if (((token === import18.AgGridColumn) && (45 === requestNodeIndex))) { return this._AgGridColumn_45_4.context; }
    if (((token === import18.AgGridColumn) && (47 === requestNodeIndex))) { return this._AgGridColumn_47_4.context; }
    if (((token === import18.AgGridColumn) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._AgGridColumn_41_4.context; }
    if (((token === import18.AgGridColumn) && (52 === requestNodeIndex))) { return this._AgGridColumn_52_4.context; }
    if (((token === import18.AgGridColumn) && (54 === requestNodeIndex))) { return this._AgGridColumn_54_4.context; }
    if (((token === import18.AgGridColumn) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 55)))) { return this._AgGridColumn_50_4.context; }
    if (((token === import18.AgGridColumn) && (59 === requestNodeIndex))) { return this._AgGridColumn_59_4.context; }
    if (((token === import18.AgGridColumn) && (61 === requestNodeIndex))) { return this._AgGridColumn_61_4.context; }
    if (((token === import18.AgGridColumn) && (63 === requestNodeIndex))) { return this._AgGridColumn_63_4.context; }
    if (((token === import18.AgGridColumn) && ((57 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._AgGridColumn_57_4.context; }
    if (((token === import19.AgGridNg2) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._AgGridNg2_39_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_39_0_0:any = this.parent.context.gridOptions;
    this._AgGridNg2_39_5.check_gridOptions(currVal_39_0_0,throwOnChange,false);
    const currVal_39_0_1:any = this.parent.context.rowData;
    this._AgGridNg2_39_5.check_rowData(currVal_39_0_1,throwOnChange,false);
    const currVal_39_0_2:any = 'multiple';
    this._AgGridNg2_39_5.check_rowSelection(currVal_39_0_2,throwOnChange,false);
    const currVal_39_0_3:any = '22';
    this._AgGridNg2_39_5.check_rowHeight(currVal_39_0_3,throwOnChange,false);
    const currVal_39_0_4:any = '';
    this._AgGridNg2_39_5.check_toolPanelSuppressValues(currVal_39_0_4,throwOnChange,false);
    const currVal_39_0_5:any = '';
    this._AgGridNg2_39_5.check_suppressRowClickSelection(currVal_39_0_5,throwOnChange,false);
    const currVal_39_0_6:any = '';
    this._AgGridNg2_39_5.check_enableColResize(currVal_39_0_6,throwOnChange,false);
    const currVal_39_0_7:any = '';
    this._AgGridNg2_39_5.check_enableSorting(currVal_39_0_7,throwOnChange,false);
    const currVal_39_0_8:any = '';
    this._AgGridNg2_39_5.check_enableFilter(currVal_39_0_8,throwOnChange,false);
    const currVal_39_0_9:any = this.parent.context.showToolPanel;
    this._AgGridNg2_39_5.check_showToolPanel(currVal_39_0_9,throwOnChange,false);
    this._AgGridNg2_39_5.detectChangesInInputProps(this,this._el_39,throwOnChange);
    const currVal_41_0_0:any = 'Employee';
    this._AgGridColumn_41_4.check_headerName(currVal_41_0_0,throwOnChange,false);
    this._AgGridColumn_41_4.detectChangesInInputProps(this,this._el_41,throwOnChange);
    const currVal_43_0_0:any = true;
    this._AgGridColumn_43_4.check_pinned(currVal_43_0_0,throwOnChange,false);
    const currVal_43_0_1:any = 30;
    this._AgGridColumn_43_4.check_width(currVal_43_0_1,throwOnChange,false);
    const currVal_43_0_2:any = true;
    this._AgGridColumn_43_4.check_checkboxSelection(currVal_43_0_2,throwOnChange,false);
    const currVal_43_0_3:any = true;
    this._AgGridColumn_43_4.check_suppressMenu(currVal_43_0_3,throwOnChange,false);
    const currVal_43_0_4:any = true;
    this._AgGridColumn_43_4.check_suppressSorting(currVal_43_0_4,throwOnChange,false);
    const currVal_43_0_5:any = '#';
    this._AgGridColumn_43_4.check_headerName(currVal_43_0_5,throwOnChange,false);
    this._AgGridColumn_43_4.detectChangesInInputProps(this,this._el_43,throwOnChange);
    const currVal_45_0_0:any = 'name';
    this._AgGridColumn_45_4.check_field(currVal_45_0_0,throwOnChange,false);
    const currVal_45_0_1:any = true;
    this._AgGridColumn_45_4.check_pinned(currVal_45_0_1,throwOnChange,false);
    const currVal_45_0_2:any = 150;
    this._AgGridColumn_45_4.check_width(currVal_45_0_2,throwOnChange,false);
    const currVal_45_0_3:any = 'Name';
    this._AgGridColumn_45_4.check_headerName(currVal_45_0_3,throwOnChange,false);
    this._AgGridColumn_45_4.detectChangesInInputProps(this,this._el_45,throwOnChange);
    const currVal_47_0_0:any = 'country';
    this._AgGridColumn_47_4.check_field(currVal_47_0_0,throwOnChange,false);
    const currVal_47_0_1:any = true;
    this._AgGridColumn_47_4.check_pinned(currVal_47_0_1,throwOnChange,false);
    const currVal_47_0_2:any = 150;
    this._AgGridColumn_47_4.check_width(currVal_47_0_2,throwOnChange,false);
    const currVal_47_0_3:any = this.parent.context.countryCellRenderer;
    this._AgGridColumn_47_4.check_cellRenderer(currVal_47_0_3,throwOnChange,false);
    const currVal_47_0_4:any = this.parent.context.getCountryFilterParams();
    this._AgGridColumn_47_4.check_filterParams(currVal_47_0_4,throwOnChange,false);
    const currVal_47_0_5:any = 'Country';
    this._AgGridColumn_47_4.check_headerName(currVal_47_0_5,throwOnChange,false);
    this._AgGridColumn_47_4.detectChangesInInputProps(this,this._el_47,throwOnChange);
    const currVal_50_0_0:any = 'IT Skills';
    this._AgGridColumn_50_4.check_headerName(currVal_50_0_0,throwOnChange,false);
    this._AgGridColumn_50_4.detectChangesInInputProps(this,this._el_50,throwOnChange);
    const currVal_52_0_0:any = 125;
    this._AgGridColumn_52_4.check_width(currVal_52_0_0,throwOnChange,false);
    const currVal_52_0_1:any = this.parent.context.skillsCellRenderer;
    this._AgGridColumn_52_4.check_cellRenderer(currVal_52_0_1,throwOnChange,false);
    const currVal_52_0_2:any = true;
    this._AgGridColumn_52_4.check_suppressSorting(currVal_52_0_2,throwOnChange,false);
    const currVal_52_0_3:any = this.parent.context.getSkillFilter();
    this._AgGridColumn_52_4.check_filter(currVal_52_0_3,throwOnChange,false);
    const currVal_52_0_4:any = 'Skills';
    this._AgGridColumn_52_4.check_headerName(currVal_52_0_4,throwOnChange,false);
    this._AgGridColumn_52_4.detectChangesInInputProps(this,this._el_52,throwOnChange);
    const currVal_54_0_0:any = 'proficiency';
    this._AgGridColumn_54_4.check_field(currVal_54_0_0,throwOnChange,false);
    const currVal_54_0_1:any = 120;
    this._AgGridColumn_54_4.check_width(currVal_54_0_1,throwOnChange,false);
    const currVal_54_0_2:any = this.parent.context.percentCellRenderer;
    this._AgGridColumn_54_4.check_cellRenderer(currVal_54_0_2,throwOnChange,false);
    const currVal_54_0_3:any = this.parent.context.getProficiencyFilter();
    this._AgGridColumn_54_4.check_filter(currVal_54_0_3,throwOnChange,false);
    const currVal_54_0_4:any = 'Proficiency';
    this._AgGridColumn_54_4.check_headerName(currVal_54_0_4,throwOnChange,false);
    this._AgGridColumn_54_4.detectChangesInInputProps(this,this._el_54,throwOnChange);
    const currVal_57_0_0:any = 'Contact';
    this._AgGridColumn_57_4.check_headerName(currVal_57_0_0,throwOnChange,false);
    this._AgGridColumn_57_4.detectChangesInInputProps(this,this._el_57,throwOnChange);
    const currVal_59_0_0:any = 'mobile';
    this._AgGridColumn_59_4.check_field(currVal_59_0_0,throwOnChange,false);
    const currVal_59_0_1:any = 150;
    this._AgGridColumn_59_4.check_width(currVal_59_0_1,throwOnChange,false);
    const currVal_59_0_2:any = 'text';
    this._AgGridColumn_59_4.check_filter(currVal_59_0_2,throwOnChange,false);
    const currVal_59_0_3:any = 'Mobile';
    this._AgGridColumn_59_4.check_headerName(currVal_59_0_3,throwOnChange,false);
    this._AgGridColumn_59_4.detectChangesInInputProps(this,this._el_59,throwOnChange);
    const currVal_61_0_0:any = 'landline';
    this._AgGridColumn_61_4.check_field(currVal_61_0_0,throwOnChange,false);
    const currVal_61_0_1:any = 150;
    this._AgGridColumn_61_4.check_width(currVal_61_0_1,throwOnChange,false);
    const currVal_61_0_2:any = 'text';
    this._AgGridColumn_61_4.check_filter(currVal_61_0_2,throwOnChange,false);
    const currVal_61_0_3:any = 'Land-line';
    this._AgGridColumn_61_4.check_headerName(currVal_61_0_3,throwOnChange,false);
    this._AgGridColumn_61_4.detectChangesInInputProps(this,this._el_61,throwOnChange);
    const currVal_63_0_0:any = 'address';
    this._AgGridColumn_63_4.check_field(currVal_63_0_0,throwOnChange,false);
    const currVal_63_0_1:any = 500;
    this._AgGridColumn_63_4.check_width(currVal_63_0_1,throwOnChange,false);
    const currVal_63_0_2:any = 'text';
    this._AgGridColumn_63_4.check_filter(currVal_63_0_2,throwOnChange,false);
    const currVal_63_0_3:any = 'Address';
    this._AgGridColumn_63_4.check_headerName(currVal_63_0_3,throwOnChange,false);
    this._AgGridColumn_63_4.detectChangesInInputProps(this,this._el_63,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_AgGridColumn_43_0.dirty) {
        this._query_AgGridColumn_43_0.reset([this._AgGridColumn_43_4.context]);
        this._AgGridColumn_43_4.context.childColumns = this._query_AgGridColumn_43_0;
        this._query_AgGridColumn_43_0.notifyOnChanges();
      }
      if (this._query_AgGridColumn_45_0.dirty) {
        this._query_AgGridColumn_45_0.reset([this._AgGridColumn_45_4.context]);
        this._AgGridColumn_45_4.context.childColumns = this._query_AgGridColumn_45_0;
        this._query_AgGridColumn_45_0.notifyOnChanges();
      }
      if (this._query_AgGridColumn_47_0.dirty) {
        this._query_AgGridColumn_47_0.reset([this._AgGridColumn_47_4.context]);
        this._AgGridColumn_47_4.context.childColumns = this._query_AgGridColumn_47_0;
        this._query_AgGridColumn_47_0.notifyOnChanges();
      }
      if (this._query_AgGridColumn_41_0.dirty) {
        this._query_AgGridColumn_41_0.reset([
          this._AgGridColumn_41_4.context,
          this._AgGridColumn_43_4.context,
          this._AgGridColumn_45_4.context,
          this._AgGridColumn_47_4.context
        ]
        );
        this._AgGridColumn_41_4.context.childColumns = this._query_AgGridColumn_41_0;
        this._query_AgGridColumn_41_0.notifyOnChanges();
      }
      if (this._query_AgGridColumn_52_0.dirty) {
        this._query_AgGridColumn_52_0.reset([this._AgGridColumn_52_4.context]);
        this._AgGridColumn_52_4.context.childColumns = this._query_AgGridColumn_52_0;
        this._query_AgGridColumn_52_0.notifyOnChanges();
      }
      if (this._query_AgGridColumn_54_0.dirty) {
        this._query_AgGridColumn_54_0.reset([this._AgGridColumn_54_4.context]);
        this._AgGridColumn_54_4.context.childColumns = this._query_AgGridColumn_54_0;
        this._query_AgGridColumn_54_0.notifyOnChanges();
      }
      if (this._query_AgGridColumn_50_0.dirty) {
        this._query_AgGridColumn_50_0.reset([
          this._AgGridColumn_50_4.context,
          this._AgGridColumn_52_4.context,
          this._AgGridColumn_54_4.context
        ]
        );
        this._AgGridColumn_50_4.context.childColumns = this._query_AgGridColumn_50_0;
        this._query_AgGridColumn_50_0.notifyOnChanges();
      }
      if (this._query_AgGridColumn_59_0.dirty) {
        this._query_AgGridColumn_59_0.reset([this._AgGridColumn_59_4.context]);
        this._AgGridColumn_59_4.context.childColumns = this._query_AgGridColumn_59_0;
        this._query_AgGridColumn_59_0.notifyOnChanges();
      }
      if (this._query_AgGridColumn_61_0.dirty) {
        this._query_AgGridColumn_61_0.reset([this._AgGridColumn_61_4.context]);
        this._AgGridColumn_61_4.context.childColumns = this._query_AgGridColumn_61_0;
        this._query_AgGridColumn_61_0.notifyOnChanges();
      }
      if (this._query_AgGridColumn_63_0.dirty) {
        this._query_AgGridColumn_63_0.reset([this._AgGridColumn_63_4.context]);
        this._AgGridColumn_63_4.context.childColumns = this._query_AgGridColumn_63_0;
        this._query_AgGridColumn_63_0.notifyOnChanges();
      }
      if (this._query_AgGridColumn_57_0.dirty) {
        this._query_AgGridColumn_57_0.reset([
          this._AgGridColumn_57_4.context,
          this._AgGridColumn_59_4.context,
          this._AgGridColumn_61_4.context,
          this._AgGridColumn_63_4.context
        ]
        );
        this._AgGridColumn_57_4.context.childColumns = this._query_AgGridColumn_57_0;
        this._query_AgGridColumn_57_0.notifyOnChanges();
      }
      if (this._query_AgGridColumn_39_0.dirty) {
        this._query_AgGridColumn_39_0.reset([
          this._AgGridColumn_41_4.context,
          this._AgGridColumn_50_4.context,
          this._AgGridColumn_57_4.context
        ]
        );
        this._AgGridNg2_39_5.context.columns = this._query_AgGridColumn_39_0;
        this._query_AgGridColumn_39_0.notifyOnChanges();
      }
    }
    this._AgGridNg2_39_5.detectChangesInHostProps(this,this._el_39,throwOnChange);
    this._AgGridColumn_41_4.detectChangesInHostProps(this,this._el_41,throwOnChange);
    this._AgGridColumn_43_4.detectChangesInHostProps(this,this._el_43,throwOnChange);
    this._AgGridColumn_45_4.detectChangesInHostProps(this,this._el_45,throwOnChange);
    this._AgGridColumn_47_4.detectChangesInHostProps(this,this._el_47,throwOnChange);
    this._AgGridColumn_50_4.detectChangesInHostProps(this,this._el_50,throwOnChange);
    this._AgGridColumn_52_4.detectChangesInHostProps(this,this._el_52,throwOnChange);
    this._AgGridColumn_54_4.detectChangesInHostProps(this,this._el_54,throwOnChange);
    this._AgGridColumn_57_4.detectChangesInHostProps(this,this._el_57,throwOnChange);
    this._AgGridColumn_59_4.detectChangesInHostProps(this,this._el_59,throwOnChange);
    this._AgGridColumn_61_4.detectChangesInHostProps(this,this._el_61,throwOnChange);
    this._AgGridColumn_63_4.detectChangesInHostProps(this,this._el_63,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._AgGridNg2_39_5.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._AgGridNg2_39_5.context.ngOnDestroy();
  }
  private _handle_click_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_7_0:any = ((<any>this._AgGridNg2_39_5.context.api.selectAll()) !== false);
    return (true && pd_7_0);
  }
  private _handle_click_10_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_10_0:any = ((<any>this._AgGridNg2_39_5.context.api.deselectAll()) !== false);
    return (true && pd_10_0);
  }
  private _handle_click_16_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_16_0:any = ((<any>this._AgGridNg2_39_5.context.columnApi.setColumnVisible('country',false)) !== false);
    return (true && pd_16_0);
  }
  private _handle_click_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_19_0:any = ((<any>this._AgGridNg2_39_5.context.columnApi.setColumnVisible('country',true)) !== false);
    return (true && pd_19_0);
  }
  private _handle_change_30_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_30_0:any = ((<any>(this.parent.context.showToolPanel = $event.target.checked)) !== false);
    return (true && pd_30_0);
  }
  private _handle_click_33_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_33_0:any = ((<any>this.parent.context.createRowData()) !== false);
    return (true && pd_33_0);
  }
}
function viewFactory_RichGridDeclarativeComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_RichGridDeclarativeComponent1(viewUtils,parentInjector,declarationEl);
}